
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danie
 */
public class AddSongsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddSongsAdmin
     */
    public AddSongsAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBImportSong = new javax.swing.JButton();
        jTFSongPath = new javax.swing.JTextField();
        jBAddSong = new javax.swing.JButton();
        jTFSongName = new javax.swing.JTextField();
        jTFArtist = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlblClose = new javax.swing.JLabel();
        JBBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 237, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Song name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel7.setText("Artist");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel8.setText("Import song");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jBImportSong.setText("Import");
        jBImportSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImportSongActionPerformed(evt);
            }
        });
        jPanel1.add(jBImportSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));
        jPanel1.add(jTFSongPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 350, -1));

        jBAddSong.setText("Add song");
        jBAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddSongActionPerformed(evt);
            }
        });
        jPanel1.add(jBAddSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, -1, -1));
        jPanel1.add(jTFSongName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 330, -1));
        jPanel1.add(jTFArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 330, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Add songs to SoundBitz!");

        jlblClose.setBackground(new java.awt.Color(74, 31, 61));
        jlblClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblClose.setText("X");
        jlblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jlblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 160));

        JBBack.setFont(new java.awt.Font("Century Gothic", 0, 27)); // NOI18N
        JBBack.setText("Back");
        JBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBackActionPerformed(evt);
            }
        });
        jPanel1.add(JBBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBImportSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImportSongActionPerformed
        //Create a JFileChooser, add a filter for images and let the user choose his profile image, setting the path in the textbox.
        JFileChooser dialogue = new JFileChooser("C:\\MEIA");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Songs", "wav");
        dialogue.setFileFilter(filter);

        File songFile;
        String songPath;

        int valor = dialogue.showOpenDialog(this);

        if (valor == JFileChooser.APPROVE_OPTION) {
            songFile = dialogue.getSelectedFile();
            
            if (!"".equals(jTFSongName.getText()) && !"".equals(jTFArtist.getText())) {
               songPath = songFile.getPath();
                File newSong = new File(songPath);
                newSong.renameTo(new File("C:/MEIA/CANCIONES/"+jTFSongName.getText()+"-" + jTFArtist.getText() + ".wav"));
                jTFSongPath.setText(newSong.getAbsolutePath()); 
            }   
        }
    }//GEN-LAST:event_jBImportSongActionPerformed

    private void jBAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddSongActionPerformed
        String songsFilePath = "C:\\MEIA\\canciones.txt";
        String binSongsFilePath = "C:\\MEIA\\bitacora_canciones.txt";
        String descSongsFilePath = "C:\\MEIA\\desc_canciones.txt";
        String descBinSongsFilePath = "C:\\MEIA\\desc_bitacora_canciones.txt";

        File songsFile = new File(songsFilePath);
        File binSongsFile = new File(binSongsFilePath);
        File descSongsFile = new File(descSongsFilePath);
        File descBinSongsFile = new File(descBinSongsFilePath);
        
        Sequential.createFiles(songsFile, descSongsFile, binSongsFile, descBinSongsFile);
        String songPath = "C:/MEIA/CANCIONES/"+jTFSongName.getText()+"-" + jTFArtist.getText() + ".wav";
                
        if (!Sequential.isMaxReorg(binSongsFile, descBinSongsFile)) {
            addToBin(Sequential.countRegisters(songsFile)+Sequential.countRegisters(binSongsFile)+1, jTFSongName.getText(), jTFArtist.getText(), songPath, binSongsFile, descBinSongsFile);
        }
        else
        {
            Sequential.Reorganization(songsFile, binSongsFile, descSongsFile, descBinSongsFile, 6);
            addToBin(Sequential.countRegisters(songsFile)+Sequential.countRegisters(binSongsFile)+1, jTFSongName.getText(), jTFArtist.getText(), songPath, binSongsFile, descBinSongsFile);
        }
        
        showMessageDialog(null, "Canción añadida exitosamente.");
    }//GEN-LAST:event_jBAddSongActionPerformed

    private void jlblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCloseMouseClicked
       
        Sequential.filesReorganization();
        System.exit(0);
    }//GEN-LAST:event_jlblCloseMouseClicked

    private void JBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBackActionPerformed
       AdminMenu myFrame = new AdminMenu();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBBackActionPerformed

    public static void addToBin(int code, String songName, String artist, String songPath, File file, File desc)
    {
         try{
            String data = code + "|" + songName + "|" + artist + "|" + songPath + "|" + AdminData.getUser() + "|" + Sequential.getDate() + "|" + "1";
        
            FileWriter fw = new FileWriter(file, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.append(data+"\n");
            bw.close();
            
            Sequential.updateDesc(file, desc, AdminData.getUser(), 6);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSongsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSongsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSongsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSongsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSongsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBack;
    private javax.swing.JButton jBAddSong;
    private javax.swing.JButton jBImportSong;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFArtist;
    private javax.swing.JTextField jTFSongName;
    private javax.swing.JTextField jTFSongPath;
    private javax.swing.JLabel jlblClose;
    // End of variables declaration//GEN-END:variables
}
