import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import org.apache.commons.io.FileUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danie
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblClose = new javax.swing.JLabel();
        JBRegister = new javax.swing.JButton();
        JBSearch = new javax.swing.JButton();
        JBBackup = new javax.swing.JButton();
        JBRefresh = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        JBAddSongs = new javax.swing.JButton();
        jTFUsername = new javax.swing.JTextField();
        jTFRole = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Welcome, admin!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Here you can change your personal information or others'.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 840, -1));

        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel10.setText("Role:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jlblClose.setBackground(new java.awt.Color(74, 31, 61));
        jlblClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblClose.setText("X");
        jPanel2.add(jlblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));

        JBRegister.setText("Register a new user");
        JBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(JBRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 520, -1));

        JBSearch.setText("Search and modify an existing user");
        JBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSearchActionPerformed(evt);
            }
        });
        jPanel2.add(JBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 520, -1));

        JBBackup.setText("Create backup");
        JBBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBackupActionPerformed(evt);
            }
        });
        jPanel2.add(JBBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 520, -1));

        JBRefresh.setText("Refresh");
        jPanel2.add(JBRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, -1, -1));

        btnLogOut.setText("Log Out");
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 770, -1, -1));

        JBAddSongs.setText("Add songs");
        JBAddSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAddSongsActionPerformed(evt);
            }
        });
        jPanel2.add(JBAddSongs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 520, -1));

        jTFUsername.setBorder(null);
        jPanel2.add(jTFUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 260, -1));

        jTFRole.setBorder(null);
        jPanel2.add(jTFRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 250, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1090, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegisterActionPerformed
        AdminRegisterFrame myFrame = new AdminRegisterFrame();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBRegisterActionPerformed

    private void JBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSearchActionPerformed
        AdminSearchFrame myFrame = new AdminSearchFrame();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBSearchActionPerformed

    private void JBBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBackupActionPerformed
        JFileChooser chooser = new JFileChooser();
        String BackUpPath;
        String creationDate = "";
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // disable the "All files" option.
        chooser.setAcceptAllFileFilterUsed(false);
        //
        File dir;
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            dir = chooser.getSelectedFile();
            
            String source = "C://MEIA";
            File srcDir = new File(source);
            
            try {
                FileUtils.copyDirectory(srcDir, dir);
                
                String bitBackupPath = "C:\\MEIA\\bitacora_backup.txt";
                String desBitBackupPath = "C:\\MEIA\\desc_bitacora_backup.txt";

                File bitBackup = new File(bitBackupPath);
                File desBitBackup = new File(desBitBackupPath);
                
                if (!bitBackup.exists()) {
                    bitBackup.createNewFile();
                    desBitBackup.createNewFile();   
                    creationDate = RegisterFrame.getDate();
                }
                Backup.createBackupBit(bitBackup, desBitBackup, dir, creationDate);


            } catch (IOException e) {
                e.printStackTrace();
}
          }
        else {
          System.out.println("No Selection.");
          }
    }//GEN-LAST:event_JBBackupActionPerformed

    private void JBAddSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAddSongsActionPerformed
        AddSongsAdmin myFrame = new AddSongsAdmin();
        myFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBAddSongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAddSongs;
    private javax.swing.JButton JBBackup;
    private javax.swing.JButton JBRefresh;
    private javax.swing.JButton JBRegister;
    private javax.swing.JButton JBSearch;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFRole;
    private javax.swing.JTextField jTFUsername;
    private javax.swing.JLabel jlblClose;
    // End of variables declaration//GEN-END:variables
}
